model:
  name: mistralai/Mistral-7B-v0.3
  torch_dtype: float16
  device_map: auto
  trust_remote_code: false

tokenizer:
  name: mistralai/Mistral-7B-v0.3
  padding_side: left
  max_length: 1280  # input + target