model:
  name: assets/models/Mistral-7B-v0.3
  torch_dtype: float16
  device_map: cuda:1 # auto, cuda:0, cpu
  trust_remote_code: false

tokenizer:
  name: assets/models/Mistral-7B-v0.3
  padding_side: left
  max_length: 1280  # input + target