ptq:
  modes:
    - name: int8
      # checkpoint_dir: "assets/models/lora_peft_merged_r2_mistral_7b_v0.3"
      checkpoint_dir: "assets/models/Mistral-7B-v0.3"
      load_in_8bit: true
      load_in_4bit: false

    - name: nf4
      # checkpoint_dir: "assets/models/lora_peft_merged_r2_mistral_7b_v0.3"
      checkpoint_dir: "assets/models/Mistral-7B-v0.3"
      load_in_8bit: false
      load_in_4bit: true
      bnb_4bit_quant_type: nf4
      bnb_4bit_compute_dtype: float16
      bnb_4bit_use_double_quant: false

    - name: gptq_int4
      # checkpoint_dir: "assets/models/GPTQ_Lora_Peft_r2_alpha_4_Mistral-7B-v0.3"
      checkpoint_dir: "assets/models/GPTQ_Mistral-7B-v0.3"
      bits: 4
      group_size: 128
      desc_act: false

    - name: awq_int4
      checkpoint_dir: "assets/models/AWQ_Lora_Peft_r2_alpha_4_Mistral-7B-v0.3"
      bits: 4
      group_size: 128
      zero_point: True
      version: GEMM